Repository VelocityIsNotSpeed/Grupo42-IntProg1, pull requests merged in 2019-07, with the labels that each got.

#16 Primeira versão de inimigo
  jogo42-cb/draw.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#14 Funcionalidade básica de level
  jogo42-cb/draw.c
  jogo42-cb/helpers.c
  jogo42-cb/jogo42-cb.cbp
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
  jogo42-cb/main.c
  jogo42-cb/mover_jog.c
Labels: funcionalidade

#23 Diretrizes de estilo de programação
  README.md
  doc/estilo.md
Labels: documentação

#25 Grande refatoração
  .gitignore
  jogo42-cb/draw.c
  jogo42-cb/helpers.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42-cb.cbp
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
  jogo42-cb/main.c
  jogo42-cb/mover_jog.c
Labels: refatoração

#26 Camera móvel centrada no jogador
  jogo42-cb/desenhar.c
  jogo42-cb/helpers.c
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
  jogo42-cb/main.c
Labels: funcionalidade

#30 Ataque e movimentação do inimigo
  jogo42-cb/desenhar.c
  jogo42-cb/inimigo.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42-cb.cbp
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#31 Ataque do jogador
  jogo42-cb/desenhar.c
  jogo42-cb/helpers.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#33 Grande refatoração e pequenas mudanças
  jogo42-cb/desenhar.c
  jogo42-cb/helpers.c
  jogo42-cb/inimigo.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
  jogo42-cb/main.c
Labels: funcionalidade, refatoração

#34 Varios inimigos
  jogo42-cb/desenhar.c
  jogo42-cb/inimigo.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#35 Funcionalidade necessária para começarmos a fazer os mapas
  jogo42-cb/desenhar.c
  jogo42-cb/estagios.h
  jogo42-cb/helpers.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42-cb.cbp
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
  jogo42-cb/main.c
Labels: WIP, assets, funcionalidade

#48 Ataque Completo
  jogo42-cb/desenhar.c
  jogo42-cb/inimigo.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#60 Estagios
  jogo42-cb/estagios.h
Labels: assets

#68 jogador
  jogo42-cb/desenhar.c
  jogo42-cb/tex/protag.png
Labels: assets

#72 paredes atravessaveis
  jogo42-cb/desenhar.c
  jogo42-cb/estagios.h
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
Labels: funcionalidade

#70 Parcialmente integrar a loja ao resto do jogo
  jogo42-cb/desenhar.c
  jogo42-cb/jogo42-cb.cbp
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
  jogo42-cb/raygui.h
  jogo42-cb/ricons.h
Labels: funcionalidade

#79 mais alcance e com mira
  jogo42-cb/desenhar.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
Labels: funcionalidade

#78 Update - Pausar
  jogo42-cb/desenhar.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#80 Termina de integrar a loja
  jogo42-cb/desenhar.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#83 Sistema de Saciedade #41
  jogo42-cb/desenhar.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade

#84 Passagem de estágio
  jogo42-cb/desenhar.c
  jogo42-cb/estagios.h
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/level.c
  jogo42-cb/main.c
Labels: funcionalidade

#85 Poções #40 #82
  jogo42-cb/desenhar.c
  jogo42-cb/inimigo.c
  jogo42-cb/jogador.c
  jogo42-cb/jogo42.h
  jogo42-cb/main.c
Labels: funcionalidade
